--- 
archives: 
  - 
    replacements: 
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows
before: 
  hooks: 
    - "go mod tidy"
    - "go generate ./..."
builds: 
  - 
    env: 
      - CGO_ENABLED=0
    goarch: 
      - amd64
      - arm
      - arm64
    goos: 
      - linux
      - windows
      - darwin
    ignore: 
      - 
        goarch: arm
        goos: windows
      - 
        goarch: arm64
        goos: windows
      - 
        goarch: arm
        goos: darwin
    main: ./cmd/zeet
changelog: 
  filters: 
    exclude: 
      - "^docs:"
      - "^test:"
  sort: asc
checksum: 
  name_template: checksums.txt
project_name: zeet
snapshot: 
  name_template: "{{ incpatch .Version }}-next"
brews:
  - tap:
      owner: zeet-dev
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"