--- 
archives: 
  - 
    replacements: 
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
before:
  hooks: 
    - "go mod tidy"
    - "go generate ./..."
builds: 
  - 
    env: 
      - CGO_ENABLED=0
    goarch: 
      - amd64
      - arm
      - arm64
    goos: 
      - linux
      - windows
      - darwin
    ignore: 
      - 
        goarch: arm
        goos: windows
      - 
        goarch: arm64
        goos: windows
      - 
        goarch: arm
        goos: darwin
    main: ./cmd/zeet
changelog: 
  filters: 
    exclude: 
      - "^docs:"
      - "^test:"
  sort: asc
checksum: 
  name_template: checksums.txt
project_name: zeet
snapshot: 
  name_template: "{{ incpatch .Version }}-next"
brews:
  -
    name: zeet
    tap:
      owner: zeet-dev
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"

    homepage: "https://zeet.co"
    description: "The Zeet CLI"
    skip_upload: auto

    custom_block: |
      head "https://github.com/zeet-dev/cli.git"
  -
    name: zeet-rc
    tap:
      owner: zeet-dev
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    homepage: "https://zeet.co"
    description: "The Zeet CLI [w/ release candidates]"
    install: |
      bin.install "zeet" => "zeet-rc"